-- HOMEPAGE NOTES
-- ---------------------------------------------------------------------------
-- This file is not a full schema import.
-- It is only here to explain what the homepage expects from your database.
--
-- Based on the uploaded project files, the homepage reads from these tables:
--   Parks(park_name, region, city, state, amenities)
--   Events(title, description, event_type, start_datetime, event_status, park_id)
--
-- If your imported tables use the schema from the uploaded SQL files,
-- the homepage will be able to query them after you create the database:
--
--   CREATE DATABASE nys_parks;
--
-- Then import your SQL files in this general order:
--   1. parks.sql
--   2. users.sql
--   3. fields.sql
--   4. events.sql
--   5. bookings.sql
--   6. attendance.sql
--   7. payments_donations.sql
--   8. employee_schedules.sql
--   9. pto_requests.sql
--
-- If the DB is not connected or there are no rows yet,
-- index.php will automatically show fallback demo content.
